[workspace]
members = [
    "fe635",
    "fe621",
    "fe680",
    "fe630"
]
resolver = "2"

[workspace.dependencies]
polars = { version = "0.46", features = ["full", "list_arithmetic"] }
cubic_spline = { version = "1" }

[profile.release]
debug = true