[package]
name = "fe680"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = { workspace = true }
cubic_spline = { workspace = true }
nalgebra = "0.33"
plotters = "0.3.7"
argmin = "0.10.0"
argmin-math = { version = "0.4.0", features = ["nalgebra_latest", "vec"] }
itertools = "0.14.0"

